
server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 1024

logging:
  level:
    org:
      flywaydb: debug
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  application:
    name: taua_travel_membership_api
  datasource:
    url: jdbc:postgresql://localhost:5432/os_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        log.non-contextual-creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: NON_NULL